AWSTemplateFormatVersion: "2010-09-09"
Description: TradingBot Single VM (EC2) - Docker+ECR+systemd; Jupyter via localhost tunnel; Ray head enabled; uses pre-existing SG

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Existing VPC ID

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for the instance
    Default: subnet-0a568c53670a616fc

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: tradingbot-notebook

  EMREC2InstanceProfileName:
    Type: String
    Default: EMR_EC2_DefaultRole

  InstanceType:
    Type: String
    Default: t3.small

  VolumeSizeGiB:
    Type: Number
    Default: 30

  VolumeIops:
    Type: Number
    Default: 3000

  AllowSshCidr:
    Type: String
    Default: "0.0.0.0/32"

  AwsRegion:
    Type: String
    Default: eu-west-2

  EcrRepoName:
    Type: String
    Default: trading-platform

  ImageTag:
    Type: String
    Default: sklearn-latest

  ExtraImageTag:
    Type: String
    Default: sklearn-5ef3d8e77fc9

  NotebookAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

  JupyterPort:
    Type: Number
    Default: 8888

  RayDashboardPort:
    Type: Number
    Default: 8265

  ShmSize:
    Type: String
    Default: "6g"

  DockerCpuLimit:
    Type: String
    Default: ""

  DockerMemoryLimit:
    Type: String
    Default: "16g"

Conditions:
  EnableSSH: !Not [!Equals [!Ref AllowSshCidr, "0.0.0.0/32"]]

Resources:
  NotebookInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref NotebookAmiId
      InstanceType: !Ref InstanceType
      KeyName: !If [EnableSSH, !Ref KeyName, !Ref "AWS::NoValue"]
      IamInstanceProfile: !Ref EMREC2InstanceProfileName

      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - sg-0a4c2cda3d4b45b35   # <-- EXISTING ray-head-node-sg
          AssociatePublicIpAddress: true
          DeleteOnTermination: true

      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            VolumeSize: !Ref VolumeSizeGiB
            Iops: !Ref VolumeIops
            Encrypted: true
            DeleteOnTermination: true

      MetadataOptions:
        HttpEndpoint: enabled
        HttpTokens: required
        HttpPutResponseHopLimit: 2
        InstanceMetadataTags: enabled

      Tags:
        - Key: Name
          Value: !Sub "tradingbot-ray-head-${AWS::StackName}"
        - Key: Project
          Value: TradingBot
        - Key: RayRole
          Value: head

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euo pipefail

          REGION='${AwsRegion}'
          REPO_NAME='${EcrRepoName}'
          IMAGE_TAG='${ImageTag}'
          EXTRA_TAG='${ExtraImageTag}'

          NOTEBOOK_DIR="/home/ec2-user/notebooks"
          CONTAINER_NOTEBOOK_DIR="/workspace"

          CONTAINER_NAME="container"
          PORT='${JupyterPort}'
          RAY_DASHBOARD_PORT='${RayDashboardPort}'
          SHM_SIZE='${ShmSize}'
          MEM_LIMIT='${DockerMemoryLimit}'

          CPU_LIMIT='${DockerCpuLimit}'
          CPU_FLAG=""
          if [ -n "$CPU_LIMIT" ]; then
            CPU_FLAG="--cpus=$CPU_LIMIT"
          fi

          dnf update -y
          dnf install -y docker amazon-ssm-agent
          systemctl enable docker
          systemctl start docker
          systemctl enable amazon-ssm-agent
          systemctl start amazon-ssm-agent

          usermod -aG docker ec2-user

          mkdir -p "$NOTEBOOK_DIR"
          chown -R ec2-user:ec2-user "$NOTEBOOK_DIR"

          ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
          ECR_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME"

          aws ecr get-login-password --region "$REGION" \
            | docker login --username AWS --password-stdin "$ECR_URI"

          docker pull "$ECR_URI:$IMAGE_TAG"
          docker pull "$ECR_URI:$EXTRA_TAG" || true

          TOKEN="$(curl -s -X PUT http://169.254.169.254/latest/api/token \
            -H 'X-aws-ec2-metadata-token-ttl-seconds: 21600')"
          EC2_PRIVATE_IP="$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
            http://169.254.169.254/latest/meta-data/local-ipv4)"

          cat >/etc/systemd/system/ray-head.service <<EOF
          [Unit]
          Description=Ray Head + Jupyter Container
          After=network-online.target docker.service
          Wants=network-online.target docker.service

          [Service]
          Restart=always
          RestartSec=5

          ExecStartPre=-/usr/bin/docker rm -f $CONTAINER_NAME

          ExecStart=/bin/bash -lc '\
            /usr/bin/docker run --name "$CONTAINER_NAME" \
              --network host \
              $CPU_FLAG \
              --memory="$MEM_LIMIT" \
              --shm-size="$SHM_SIZE" \
              --ulimit memlock=-1 \
              --ulimit nofile=1048576:1048576 \
              -v "$NOTEBOOK_DIR:$CONTAINER_NOTEBOOK_DIR" \
              -e AWS_REGION="$REGION" \
              "$ECR_URI:$IMAGE_TAG" \
              bash -lc " \
                ray start --head \
                  --node-ip-address=$EC2_PRIVATE_IP \
                  --port=6379 \
                  --dashboard-host=127.0.0.1 \
                  --dashboard-port=$RAY_DASHBOARD_PORT \
                  --min-worker-port=20000 \
                  --max-worker-port=20100 \
                  --disable-usage-stats && \
                exec jupyter lab --no-browser \
                  --ip 127.0.0.1 \
                  --port $PORT \
                  --allow-root \
                  --notebook-dir=$CONTAINER_NOTEBOOK_DIR \
                  --IdentityProvider.token='\'''\'' \
                  --ServerApp.password='\'''\'' \
              " \
          '

          ExecStop=/usr/bin/docker stop $CONTAINER_NAME

          [Install]
          WantedBy=multi-user.target
          EOF

          systemctl daemon-reload
          systemctl enable ray-head.service
          systemctl restart ray-head.service

Outputs:
  InstanceId:
    Value: !Ref NotebookInstance

  PrivateIp:
    Value: !GetAtt NotebookInstance.PrivateIp

  PublicIp:
    Value: !GetAtt NotebookInstance.PublicIp
