version: 0.2

env:
  variables:
    AWS_REGION: eu-west-2
    ECR_REPO: trading-platform
    IMAGE_TAG: emr-7.11.0-pyarrow-1
    IMAGE_DIR: infra/images/emr-serverless-spark-pyarrow

phases:
  pre_build:
    commands:
      - set -euo pipefail
      - echo "Region: ${AWS_REGION}"
      - ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
      - echo "Account: ${ACCOUNT_ID}"
      - echo "Ensuring ECR repo exists: ${ECR_REPO}"
      - aws ecr describe-repositories --region "${AWS_REGION}" --repository-names "${ECR_REPO}" >/dev/null 2>&1 || aws ecr create-repository --region "${AWS_REGION}" --repository-name "${ECR_REPO}" >/dev/null
      - aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"
      - echo "ECR_URI=${ECR_URI}"
  build:
    commands:
      - cd "${CODEBUILD_SRC_DIR}/${IMAGE_DIR}"
      - echo "Building from: $(pwd)"
      - docker build -t "${ECR_REPO}:${IMAGE_TAG}" .
      - docker tag "${ECR_REPO}:${IMAGE_TAG}" "${ECR_URI}:${IMAGE_TAG}"
  post_build:
    commands:
      - echo "Pushing: ${ECR_URI}:${IMAGE_TAG}"
      - docker push "${ECR_URI}:${IMAGE_TAG}"
      - echo "DONE. Image: ${ECR_URI}:${IMAGE_TAG}"


# version: 0.2

# env:
#   variables:
#     AWS_REGION: eu-west-2
#     ECR_REPO: trading-platform
#     IMAGE_TAG: emr-7.11.0-pyarrow-1
#     IMAGE_DIR: infra/images/emr-serverless-spark-pyarrow

# phases:
#   pre_build:
#     commands:
#       - set -euo pipefail
#       - echo "Region: $AWS_REGION"
#       - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
#       - echo "Account: $ACCOUNT_ID"
#       - echo "Ensuring ECR repo exists: $ECR_REPO"
#       - aws ecr describe-repositories --region "$AWS_REGION" --repository-names "$ECR_REPO" >/dev/null 2>&1 || \
#         aws ecr create-repository --region "$AWS_REGION" --repository-name "$ECR_REPO" >/dev/null
#       - aws ecr get-login-password --region "$AWS_REGION" | \
#         docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
#       - ECR_URI="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO"
#       - echo "ECR_URI=$ECR_URI"
#   build:
#     commands:
#       - cd "$CODEBUILD_SRC_DIR/$IMAGE_DIR"
#       - echo "Building from: $(pwd)"
#       - docker build -t "$ECR_REPO:$IMAGE_TAG" .
#       - docker tag "$ECR_REPO:$IMAGE_TAG" "$ECR_URI:$IMAGE_TAG"
#   post_build:
#     commands:
#       - echo "Pushing: $ECR_URI:$IMAGE_TAG"
#       - docker push "$ECR_URI:$IMAGE_TAG"
#       - echo "DONE. Image: $ECR_URI:$IMAGE_TAG"
